### ISSUE TITLE
Flagd provider

### ISSUE THREAD

**Issue by alxckn** [open-feature/ruby-sdk#117]
Hello,

Is a [flagd](https://flagd.dev/) ad-hoc provider considered for this SDK? Would contributions on this be welcome?

**Comment by beeme1mr** [comment]
Hey @alxckn, providers are not included within the SDK with the exception of the no-op and in-memory providers, because they're used for usability and testing improvements. We keep providers and hooks in a [separate repo](https://github.com/open-feature/ruby-sdk-contrib/tree/main). There's already a basic flagd implementation but it's very likely out of date given the recent changes made to the Ruby SDK. Any contributions you're willing to make would be greatly appreciated. Thanks!

By the way, please consider joining the #openfeature-ruby Slack channel on the CNCF workspace. It's a great way to connect with other contributors.

**Comment by alxckn** [comment]
Hello @beeme1mr , thanks for pointing me towards this repo. I did a first checkout and proposed a small cleanup PR to get things started: https://github.com/open-feature/ruby-sdk-contrib/pull/13
